services:
  mtproxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproto-proxy
    restart: unless-stopped
    ports:
      - "993:443"
    volumes:
      - proxy-config:/data
    environment:
      # - TAG=
      - WORKERS=2

volumes:
  proxy-config:
